name: Update franchises

on:
  workflow_dispatch:
  schedule:
  - cron: "0 10-22/2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    
    - run: npm ci
    - run: npm run franchises
    - run: |
        git add meta
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "Update franchises"
        git push
